### ISSUE TITLE
'bootstrap4' is not a registered tag library. Must be one of:

### ISSUE THREAD

**Issue by sookyeomKim** [monim67/django-bootstrap-datepicker-plus#10]
![2018-10-04 3 57 48](https://user-images.githubusercontent.com/8381017/46457713-5232b980-c7ee-11e8-88f0-8b6bbb3378ee.png)
![2018-10-04 3 58 04](https://user-images.githubusercontent.com/8381017/46457718-55c64080-c7ee-11e8-8a94-038c161eb566.png)

what problem...?

**Comment by monim67** [comment]
You need to install `django-bootstrap4`

     pip install django-bootstrap4

**Comment by dspacejs** [comment]
@monim67 installing `django-bootstrap4` didn't fix it for me

**Comment by rhoerbe** [comment]
I did install django-bootstrap4 and restart runserver - problem persists

**Comment by CurtlyCritchlow** [comment]
@rhoerbe I did what you suggested it solved the problem but not i'm getting
```Could not parse the remainder: '% load bootstrap4 %' from '% load bootstrap4 %' ```

I'm not sure what is wrong now.

**Comment by monim67** [comment]
@CurtlyCritchlow the syntax to load bootstrap tag is `{% load bootstrap4 %}`, not `{{% load bootstrap4 %}}`.

**Comment by CurtlyCritchlow** [comment]
@monim67 my code html code is 
```{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }} ```

I'm using django 2.2 and the documentation is up to 2.1 can this be the problem
my settings.py code is
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'bootstrap_datepicker_plus',
    'bootstrap4',
    'general.apps.GeneralConfig',
    'laboratory.apps.LaboratoryConfig',
]
```
my forms.py 
```
from bootstrap_datepicker_plus import DatePickerInput, DateTimePickerInput

class RequisitionForm(ModelForm):
    class Meta:
        model = Requisition
        fields = '__all__'
        widgets = {
            'illness_date': DatePickerInput,
        }
```

**Comment by seriadiallo** [comment]
> You need to install `django-bootstrap4`
> 
> ```
>  pip install django-bootstrap4
> ```

thank you a lot

**Comment by jonatascs** [comment]
INSTALLED_APPS = (
    # ...
    "bootstrap4",
    # ...
)

**Comment by Shincham** [comment]
Tried all the solutions here but i'm still getting the error.

**Comment by Rahma979** [comment]
@Shincham  me too i installed bootstrap and bootstrap4 and i added them in installed apps in settings.py but i still get the same error :(

**Comment by Ashish-Waykar** [comment]
"bootstrap4", put this in your mainProject/settings.py

INSTALLED_APPS = (
    # ...
    "bootstrap4",
    # ...
)

**Comment by DnyaneshwarMadake** [comment]
'bootstrap4' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache humanize i18n l10n log static tz 

on cmd pip install  django-bootstrap4 but same error will be shown..

![boot](https://user-images.githubusercontent.com/87903257/129433823-5c6ab028-ba7e-4ba1-9116-7952c4aac10f.png)

**Comment by Eliusa0997** [comment]
you need to install django-bootstrap4 not bootstrap4
use the command 
pip install django-bootstrap4

**Comment by snowyyyyyyyyyy** [comment]
you are right!!!

**Comment by SK-4** [comment]
still not working getting the error Invalid filter: 'bootstrap4'
