### ISSUE TITLE
Dimensions of the Date & Time Picker

### ISSUE THREAD

**Issue by marcosfreccia** [monim67/django-bootstrap-datepicker-plus#11]
I have a very simple question.

Is it possible to redimension the size of the Date and Time Picker?

![image](https://user-images.githubusercontent.com/29305097/46583806-67148480-ca5c-11e8-95ca-53ee19aecf93.png)

For example, I would like that the Date Picker could have a shorter width. The same would apply for the Time Picker.

Thanks!

**Comment by monim67** [comment]
Put them inside smaller containers, like col-md-3 or 4.

**Comment by marcosfreccia** [comment]
Hi @monim67, the problem is how I render my form I believe.

        <tr>
            
            <td>Date & Time Restore *</td>
            <td><div class="row"><div class="col-sm-5">{{form.date_restore}}</div></div></td>
            <td><div class="row"><div class="col-md-5">{{form.time_restore}}</div></div></td>
        </tr>

Which still gives me this.

![image](https://user-images.githubusercontent.com/29305097/46604300-0c2f6b80-caf6-11e8-8034-a28732eee799.png)

Any ideas?

**Comment by monim67** [comment]
Because you are using table layout. Don't know which bootstrap version you are using, you need to use bootstrap grid layout.
