### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by samuelcalegari** [monim67/django-bootstrap-datepicker-plus#115]
Hello !
in Google Chrome Console a warning message appears :

[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

I use :
Django==5.0
django-bootstrap-datepicker-plus==5.0.5

Thanh u so much

**Comment by gregorywajntrob** [comment]
Hi @monim67, thanks for the fix. Any chance this could be released?

**Comment by gregorywajntrob** [comment]
Thanks a lot, this made my life so much easier
