### ISSUE TITLE
Datepicker rendering

### ISSUE THREAD

**Issue by dcampeao** [monim67/django-bootstrap-datepicker-plus#13]
I have followed all the instructions but was unable to make the datepicker show up.
After some research I've found your answer in https://stackoverflow.com/questions/48576784/django-form-django-bootstrap-datepicker-plus-is-not-rendering-datepicker
 
In this answer there is a slightly different instruction: 

To include this at the form template made it work:
```
{% block extrahead %}   {# Extra Resources Start #}
{{ form.media }}        {# Form required JS and CSS #}
{% endblock %}          {# Extra Resources End #}
```

For me it worked. I would suggest to include this as part of the instructions in the readme file.
Otherwise, thanks for the excelent package.

**Comment by monim67** [comment]
The README file already has the instructions detailed, but not yet a good one. I have also included a `demo_project` in the repository for people to better understand the usage. Still people often get confused and puzzled. I will try my best to improve it further.

If you have any suggestions to improve it please leave a comment here #9.

**Comment by monim67** [comment]
I have updated the documentation experience. What do you think about it?

**Comment by dcampeao** [comment]
I think it's better. The docs are much more complete now. Thanks!
But I noticed that the extrahead block was not included in the docs. Isn't it necessary?
In my case, including only {{form.media}} wouldn't work. The datepicker only worked with the extrahead block.
Also, when I set debug mode to False in Django it seems that the datepicker is affected and stops showing up. Should I open a new issue on that?

**Comment by monim67** [comment]
The `extrahead` block is needed if you are using a master template. The docs refer both scenarios. You have to choose your preferences. I hoping to save hours of people trying to understand this package now :)

It works fine for me when debug is set to `FALSE`. Can you verify this is a bug from this package? If so it should go to a new issue.

**Comment by dcampeao** [comment]
Indeed, I'm using a master template. Thank you for the clarification. 
About the other issue, I had included {% load static %} only in the master template, but I should have included also in the other templates. That solved the problem!
Now everything is working fine.
Thank you very much for the support and for improving the documentation!

**Comment by NurseCode** [comment]
Greetings,  Has bootstrap 5 changed the process?  I've been working with this for two days to no avail.  The calendar icon is missing from the render page.  I've tried all of the earlier tags recommended.  
Thank you for preparing this useful tool.
