### ISSUE TITLE
datepicker-plus button not launching 

### ISSUE THREAD

**Issue by Adfitzwa** [monim67/django-bootstrap-datepicker-plus#17]
**Describe the problem**
it looks like the js is not launching on the datepicker 

**Console errors**
- No error on django console.
- No error on JavaScript console.

**HTML page:**
`{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{{ order_form.media }}

  <form method="post">
    {% csrf_token %}
    <div class="form-row">
    <div class="form-group col-md-2 mb-0">
    {{ order_form.order_location|as_crispy_field }}
    </div>
    </div>

<div class="form-row" >
 <div class="form-group col-md-2 mb-0">
{{ order_form.collection_date|as_crispy_field }}

 </div>
    </div>

</form>

{% endblock %}

`
**forms.py**
`from bootstrap_datepicker_plus import DateTimePickerInput

class ORDERForm(forms.Form):
 collection_date = forms.DateField(widget=DateTimePickerInput())
`

scripts from base.html
`        
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
`

**Comment by Adfitzwa** [comment]
![capture](https://user-images.githubusercontent.com/42683737/51867032-83447600-2318-11e9-9936-936b8e543501.PNG)

**Comment by Adfitzwa** [comment]
I tried following and getting the same issues.

**Views:**
![image](https://user-images.githubusercontent.com/42683737/51868460-1a5efd00-231c-11e9-8af1-704a38ea09bc.png)

**Forms:**
![image](https://user-images.githubusercontent.com/42683737/51868498-2945af80-231c-11e9-8991-2490484fedd1.png)

**HTML:**
![image](https://user-images.githubusercontent.com/42683737/51868533-395d8f00-231c-11e9-8726-e22f9927c0b1.png)

**Page:**
![image](https://user-images.githubusercontent.com/42683737/51868552-45e1e780-231c-11e9-8341-99a8f63d06c9.png)

**Comment by monim67** [comment]
Have you completed the walk-through tutorial successfully?

**Comment by ddurham4** [comment]
I deleted datepicker-plus from our project (mine and Adfitzwa's) and re-added it, then I worked through the tutorial on a separate server and compared them side by side. I noticed that it was using datepicker-widget.css, which didn't exist in our project. I manually added the files to our project by copying them from this git repo. The datepicker is showing up now. 
![image](https://user-images.githubusercontent.com/10453330/51915626-93f0fc80-23a9-11e9-8f18-0c285b39401c.png)

**Comment by monim67** [comment]
I am glad that you figured it out, but should not the widget CSS exist on the server too? what server are you using? Did you install the package on that server? It can really help me figure out for future fixes.

**Comment by Adfitzwa** [comment]
we thought the same thing that's why we struggled for so long, we are hosted in pythonanywhere.com - we did both PIP installs and imported the widget. for some reason it could not find it.

**Comment by monim67** [comment]
Updated the documentation about this issue, see [Troubleshooting](https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html#fix-404-not-found-errors) section.

**Comment by vitug110510** [comment]
i have same issue ? how do you solve this issue ?
