### ISSUE TITLE
The component is broken when no internet connection available

### ISSUE THREAD

**Issue by hoefling** [monim67/django-bootstrap-datepicker-plus#20]
**Describe the bug**
I need to host the website in a local network without internet access. Since `bootstrap-datetimepicker-plus` loads resources from CDN, the component can't be rendered. I can introduce a quick and dirty fix by monkeypatching the `BasePickerInput` early enough e.g.:

```python3
import bootstrap_datepicker_plus as bdp


bdp.BasePickerInput.Media.js = (
    'assets/js/moment-with-locales.min.js',
    'assets/js/bootstrap-datetimepicker.min.js',
    'bootstrap_datepicker_plus/js/datepicker-widget.js'
)
bdp.BasePickerInput.Media.css = {
    'all': (
	'assets/css/bootstrap-datetimepicker.css',
        'assets/css/bootstrap-datetimepicker-plus-override.css',
        'bootstrap_datepicker_plus/css/datepicker-widget.css',
    ),
}
```

and replacing `bootstrap-datetimepicker-plus.css` with a copy with modified font paths, but this is no solution and will break immediately once the library changes.

**To Reproduce**

1. 
```sh
$ echo -e "127.0.0.1	cdnjs.cloudflare.com" >> /etc/hosts
$ echo -e "127.0.0.1	maxcdn.bootstrapcdn.com" >> /etc/hosts
```
2. The component is not loaded correctly (missing icons, button not clickable), network errors in browser logs:
```
GET https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css net::ERR_CONNECTION_REFUSED
localhost/:70 GET https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js net::ERR_CONNECTION_REFUSED
localhost/:71 GET https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js net::ERR_CONNECTION_REFUSED
localhost/:1 GET http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff2 net::ERR_CONNECTION_REFUSED
jquery-3.3.1.min.js:2 jQuery.Deferred exception: $element.datetimepicker is not a function TypeError: $element.datetimepicker is not a function
    at HTMLInputElement.<anonymous> (http://localhost:8000/static/bootstrap_datepicker_plus/js/datepicker-widget.js:14:38)
    at Function.each (http://localhost:8000/static/assets/js/jquery-3.3.1.min.js:2:2573)
    at w.fn.init.each (http://localhost:8000/static/assets/js/jquery-3.3.1.min.js:2:1240)
    at HTMLDocument.<anonymous> (http://localhost:8000/static/bootstrap_datepicker_plus/js/datepicker-widget.js:7:38)
    at l (http://localhost:8000/static/assets/js/jquery-3.3.1.min.js:2:29375)
    at c (http://localhost:8000/static/assets/js/jquery-3.3.1.min.js:2:29677) undefined
```

**Expected behavior**
The component must be functional when on internet access available

**Setup Information (please complete the following information):**
 - OS: Fedora 29
 - Browser chrome
 - Browser version 72
 - Python version 3.6
 - Django version 2.1.5
 - Bootstrap version 4
 - jQuery version 3.3.1

**Comment by monim67** [comment]
See the [instructions here](https://monim67.github.io/django-bootstrap-datepicker-plus/configure/). Select "I will add myself" for jQuery and Bootstrap, then add them to your template from your local server.

**Comment by hoefling** [comment]
If you mean `jQuery` or `bootstrap` themselves, I already bundle them and the datetimepicker works like a charm. I meant the `moment-with-locales`, `bootstrap-datetimepicker` in `_base.py` and the glyphicons fonts in `datepicker-widget.css` which I'd like to serve locally.

**Comment by monim67** [comment]
So it is working now?

**Comment by hoefling** [comment]
No, because the URLs in the code are hardcoded and not configurable. It only "works" via monkeypatching `BasePickerInput` and `datepicker-widget.css` as mentioned above.

**Comment by hoefling** [comment]
Relevant spots in code:

https://github.com/monim67/django-bootstrap-datepicker-plus/blob/55819bf12507c98dba91c702e224afd9bae3ef9a/bootstrap_datepicker_plus/_base.py#L53-L64

https://github.com/monim67/django-bootstrap-datepicker-plus/blob/55819bf12507c98dba91c702e224afd9bae3ef9a/bootstrap_datepicker_plus/static/bootstrap_datepicker_plus/css/datepicker-widget.css#L1-L9

**Comment by monim67** [comment]
It is better for everyone to serve files from CDN. As your project is offline, you need to serve these files from your static files directory, and edit the widget CSS file.

**Comment by hoefling** [comment]
At least in the `BasePickerInput`, the media files could be configurable via settings.

**Comment by monim67** [comment]
I understand your issue, editing installed packages is not good practice. But setting resources through options will only solve it partially for you but add complexity to current code.

You can copy the bootstrap_datepicker_plus directory to your project root as an app to your project, edit it to your requirement, include the directory into your source control, that will be best suited for you.

**Comment by hoefling** [comment]
As you wish.

**Comment by monim67** [comment]
> At least in the `BasePickerInput`, the media files could be configurable via settings.

It will be available in the next release within a month or two.

**Comment by Phyks** [comment]
Hi,

I'm having the same issue. Being able to reliably force load the medias from local assets would be really great. Any news on the next release? Thanks!

**Comment by monim67** [comment]
I am gonna do it the first thing whenever I get time, kind of work-loaded right now. Mean-while if you are okay to use flatpickr instead, you can use [django-flatpickr](https://github.com/monim67/django-flatpickr) which has this feature built into it. We are thinking of importing that feature into this project soon.

**Comment by MauricioFarias** [comment]
> Hi,
> 
> I'm having the same issue. Being able to reliably force load the medias from local assets would be really great. Any news on the next release? Thanks!

Hi, I'm having the same issue too.

**Comment by monim67** [comment]
Resolved [here](https://github.com/monim67/django-bootstrap-datepicker-plus/issues/76#issuecomment-1312538257).
