### ISSUE TITLE
Date invalid with django class view

### ISSUE THREAD

**Issue by Tjorriemorrie** [monim67/django-bootstrap-datepicker-plus#24]
The picker appears correctly and posts the value correctly. However, the validation from a class based django view says the value is not valid.

```
class CreateProfileView(LoginRequiredMixin, CreateView):
    form_class = CreateProfileForm
    template_name = 'fnf/create_profile.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
```

```
class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['gender', 'birthdate']
        widgets = {
            'birthdate': DatePickerInput(format='%Y/%m/%d', options={
                "maxDate": (date.today() - relativedelta(years=18)).strftime('%Y-%m-%d'),
                "minDate": (date.today() - relativedelta(years=99)).strftime('%Y-%m-%d'),
                # "defaultDate": ().strftime('%Y-%m-%d')
            }),
        }
```

The breakpoints in `form_valid` does not trigger, so I'm not sure where the validation fails before that?

**Comment by Tjorriemorrie** [comment]
I think it is the format options causing the problem. I assumed it should be working, can you please direct me on how to solve this format issue of the date? What should I be using? I'll need to do i10n later as well

**Comment by monim67** [comment]
I guess your issue is same as #15.

**Comment by morenoh149** [comment]
issue #15 is marked as closed. We have mentioned how to use a custom format at https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Usage.html#customize-datepicker-format

But I'm now running into an issue when using a cbv
```
# views.py
class MeetingUpdate(UpdateView):
    model = Meeting
    fields = ["start", "incomplete_reason", "is_complete"]
    success_url = "/"

# forms.py
class MeetingForm(forms.ModelForm):
    start = forms.DateTimeField(
        input_formats=["%m/%d/%Y %I:%M%p"],
        widget=DateTimePickerInput(format="%m/%d/%Y %I:%M%p"),
    )

    class Meta:
        model = Meeting
        fields = [
            "start"
        ]
```
The form at `templates/meeting_form.html` shows the error
```
Enter a valid date/time.
```
how do we use custom datetime format with an UpdateView?

**Comment by monim67** [comment]
Closing as it does not affect recent releases.
