### ISSUE TITLE
datepicker not working in a formsets

### ISSUE THREAD

**Issue by KrzysztofW** [monim67/django-bootstrap-datepicker-plus#26]
Datepickers do not show up in dynamically added empty formsets.
They do show up only in formsets that are loaded with  the page.

**To Reproduce**
Create a django form with a date field:
my_date = forms.DateField(widget=DatePickerInput())
Use it in a formset.

**Expected behavior**
Statically and dynamically loaded date fields should make a JS calendar appear.

**What's seen instead**
Only the statically loaded datepickers show the JS calendar. Nothing shows up on dynamically added formsets.

**Setup Information:**
 - OS: [ubuntu 18]
 - Browser: Chrome
 - Browser version [Version 71.0.3578.80]
 - Python version [3.6]
 - Django version [2.1]
 - Bootstrap version [4]
 - jQuery version [1.7.1]

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

[configuration_page]: https://monim67.github.io/django-bootstrap-datepicker-plus/configure/
[troubleshooting_page]: https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html

**Comment by KrzysztofW** [comment]
FYI, the issue is that there is no associated 'change' event in the generated code of added datepickers. Is there any JS piece of code that should be run in order to add the events to the new datepickers?
Thank you.

**Comment by monim67** [comment]
Sorry there is no cleaner solution for that. Can you specify which library you are using to generate dynamic inputs?

**Comment by Bloodmallet** [comment]
I'm facing the same issue. I'm not using a library to generate the dynamic inputs. I'm cloning and updating the necessary elements myself. It would be very helpful if there were a callable function, that would re-search the page and associate all pickers anew.

**Comment by widg3tt** [comment]
Would you be able to provide any more details on how you were able to get this to work? I am facing the same issue using the django-dynamic-formset package and have not found a solution yet. I am using the django-bootstrap-datepicker-plus.

**Comment by Bloodmallet** [comment]
If I remember correctly I copied the content of `js/datepicker-widget.js` into my own file somewhere and called the function manually after cloning the element. I no longer have access to the code, so I can't help further than this.

**Comment by JDBasic** [comment]
Anybody found a solution to this problem?

**Comment by anoopksharma22** [comment]
I used widget_tweaks to overide type as date:

` {% for field in form.visible_fields %}
                        {% if field.label == 'From date' or field.label == 'To date' %}
                            <div class="mt-2">{{ field.label }}</div>
                            <div>{% render_field field type="date" class+="form-control" %}</div>
                        {% else %}
                            <div class="mt-2">{{ field.label }}</div>
                            <div>{% render_field field class+="form-control" %}</div>
                        {% endif %}
                    {% endfor %}`

**Comment by monim67** [comment]
From version 5.0.0 the widgets works with [django-dynamic-formset](https://github.com/elo80ka/django-dynamic-formset).
