### ISSUE TITLE
date-picker button is not clickable and the calendar does not open

### ISSUE THREAD

**Issue by samirtendulkar** [monim67/django-bootstrap-datepicker-plus#3]
The widget is working in one of my Model Form in one page. But in another of my Model form in another page it is not working. The button is not clickable and the calendar does not open.  

**Here is my template** 

```
{% extends 'base.html' %}
{% block body %}
{% load bootstrap3 %}
{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %}              {# Extra Resources End #}


<h2>Complete | Edit your profile </h2>
{{ fielderrors }}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form user_form %}
    {% bootstrap_form profile_form %}
    <input style="float:right" type="submit" value="Save Changes" class="btn btn-success"/>

</form><br/><br/><br/><br/>

{% endblock %}
```

**forms.py** 

```
class ProfileEditForm(forms.ModelForm): #UserProfileForm or ProfileEdit
    bio = forms.TextInput()

    class Meta:
        model = Profile
        fields = ('city', 'state', 'country', 'street_address', 'zip_code', 'phone_number', 'age', 'profile_image',
                  'bio', 'bio_images')
        widgets = {
            'age': DatePickerInput(),
        }
```

**Comment by monim67** [comment]
The only difference I see here that you are using 2 forms where it is not working, does it work when you remove the user_form and use the profile form only?

**Comment by samirtendulkar** [comment]
I tried removing the user_form to see if that was the issue. But its still the same. even after removing the   user_form. The date is not clickable and does not show the calendar 

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}   
    {% bootstrap_form profile_form %}
    <input style="float:right" type="submit" value="Save Changes" class="btn btn-success"/>
</form>

**Comment by monim67** [comment]
Do you see any errors in JavaScript console? Is `age` a `DateField`?

**Comment by samirtendulkar** [comment]
Yes in my models and by forms
```
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ....
    age = models.DateField(blank=True, null=True)
```

**Comment by samirtendulkar** [comment]
The console is empty no errors

**Comment by monim67** [comment]
Can you upload your project so that I can have a look? What version of django and datepicker are you using?

**Comment by samirtendulkar** [comment]
Django 1.11 and 3.0.4 of datepicker-plus. I won't be able to give you the entire project. But if you need to take a look at any part of it I will be happy to paste the code, example models, views, templates or any other detail

**Comment by monim67** [comment]
If you can provide paste-bin of the generated HTML source, I can take a look.

**Comment by samirtendulkar** [comment]
https://pastebin.com/0KDB7P39  

Above is the HTML source like you requested

**Comment by monim67** [comment]
The date-picker JavaScript and CSS files are not present in your HTML dump, that means `{{ form.media }}` tag is not present in your layout or not working.

I can also see there are 2 jQuery files included in it (3.3.1, 2.2.4). jQuery does recommend using multiple version in the same page. It can raise unexpected results as discussed in [this stack-overflow question](https://stackoverflow.com/q/48576784/9276329).

**Comment by samirtendulkar** [comment]
Below is my base.html head  (3.3.1) is coming from the code below. I don't know where is 2.2.4 coming from  
    `<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>` Is it coming from date-picker JavaScript, Bootstrap  JavaScript. Also it is working with the other form you can see both the templates are the same.  This is the pastebin of the working form

**https://pastebin.com/HZSfLQYR** 

_Below is the <head> in my base.html_
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Khal {% endblock %}</title>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
```

**Comment by samirtendulkar** [comment]
I am sorry that was the wrong pastebin. I fixed it. But it still does not click on the calendar   

https://pastebin.com/0URBa6qg

**Comment by samirtendulkar** [comment]
Below is my base.html head (3.3.1) is coming from the code below. I don't know where is 2.2.4 coming from
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>` Is it coming from date-picker JavaScript, Bootstrap JavaScript. Also it is working with the other form you can see both the templates are the same. 

**This is the pastebin of the working form
https://pastebin.com/HZSfLQYR**

Below is the in my base.html

```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Khal {% endblock %}</title>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
```

**Comment by monim67** [comment]
Change the following code

    {% block extrahead %}       {# Extra Resources Start #}
    {{ form.media }}            {# Form required JS and CSS #}
    {% endblock %}              {# Extra Resources End #}

To

    {% block extrahead %}       {# Extra Resources Start #}
    {{ user_form.media }}       {# User Form required JS and CSS #}
    {{ profile_form.media }}    {# Profile Form required JS and CSS #}
    {% endblock %}              {# Extra Resources End #}

**Comment by samirtendulkar** [comment]
Yes! Yes! Yes! Yes! that worked awesome. Thank you so so much

**Comment by samirtendulkar** [comment]
I am  sorry I did not pay close attention to that. Again thanks a ton
