### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by rg-software** [monim67/django-bootstrap-datepicker-plus#34]
I would truly appreciate a good advice in my problem. I want to handle events of the datepicker, but events aren't covered in the documentation.

I only need a simple JS function call for HTML DOM events, so I expected this code to work:

`self.fields['my_calendar'].widget.attrs['onchange'] = 'checkDate();'`

It renders correctly in HTML, but the `onchange` event is never generated! Same with `onselect`. Is there anything I can do?

**Comment by monim67** [comment]
From version 5.0.0 event handlers can be registered. Details on [customization](https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/customization.html).
