### ISSUE TITLE
Initial value of field not used

### ISSUE THREAD

**Issue by thommor** [monim67/django-bootstrap-datepicker-plus#36]
**Describe the bug**
When attempting to update a form where a date field already has a value the DatePickerInput widget doesn't display the previous value. The value is correctly passed to the widget and appears inside the input.

Once you select the widget it sets the date to today rather than the value.

**Expected behavior**
The initial value should be displayed when the form loads

**Screenshots**
<img width="651" alt="Screenshot 2019-06-25 at 13 51 55" src="https://user-images.githubusercontent.com/45167957/60099954-9edd6c80-9750-11e9-9993-5fbdfcb8afcb.png">

<img width="539" alt="Screenshot 2019-06-25 at 13 52 26" src="https://user-images.githubusercontent.com/45167957/60099921-8cfbc980-9750-11e9-8c7c-70514ba04633.png">

**Comment by monim67** [comment]
You see the date value does not match the date-format settings, that's why the value is not showing up. Please follow the README and docs to set the desired date format.
