### ISSUE TITLE
Ubuntu pip error. "Could not find a version that satisfies the requirement django-bootstrap-datepicker-plus"

### ISSUE THREAD

**Issue by samirtendulkar** [monim67/django-bootstrap-datepicker-plus#4]

**Comment by n3cr0Tech** [comment]
I'm getting the same error after I tried to install it with the command:
`pip install django-bootstrap-datepicker-plus`

Has this issue been resolved? Please advise

**Comment by Vchourey** [comment]
I am getting the same error in python 3, does  it support python3?.
