### ISSUE TITLE
widget breaks submit button

### ISSUE THREAD

**Issue by dchallsworth** [monim67/django-bootstrap-datepicker-plus#40]
Hi - not sure if this is an issue or not - probably my implemenation (I'm a beginner).

When I include the widget in my forms.py the submit button on my template no longer works - works fine when I remove datetimepicker. I wondered if there's a clash with the javascript somewhere? Could you take a look? I've added you as a colab for the project

Also, is there any way of making todays date autopopulate the field?

Thank you - it's a great app

David

**Comment by dchallsworth** [comment]
Hey

First problem was just that the default date for django was different to the formatted date for datepicker

Still can’t get a default though.

Thanks

David

**Comment by monim67** [comment]
There's a `defaultDate` option which can be used to set the dates to today.
