### ISSUE TITLE
Add Rich Text to same form

### ISSUE THREAD

**Issue by jtangir87** [monim67/django-bootstrap-datepicker-plus#41]
Not really a datepicker issue but hoping someone can help me. After I integrated django-tinymce the datepicker widget breaks and doesn't show. If I remove the field for the rich text from my form, datepicker works completely. Any suggestions??

**Comment by monim67** [comment]
Closing pre v5 issues as stale. From v5 the error messages are more informative and conflicting resources can be disabled.
