### ISSUE TITLE
Date Picker not showing

### ISSUE THREAD

**Issue by mjain-sps** [monim67/django-bootstrap-datepicker-plus#49]
**Describe the problem**
A clear and concise description of what the scenario is.
I am unable to see the datepicker in my model form.
**To Reproduce**
******my forms.py is as under********
{%extends 'mis/base.html'%}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #} -->

{% block content%}
<h4 class="display-4">Add / Modify Customer</h4>

<form class="" action="" method="post">{% csrf_token %}

  <div class="container">
    <div class="row">
      <div class="col-sm-4">
         {% bootstrap_form form %}
  
        <br>
        <a class="btn btn-primary btn-sm" href="{% url 'customer'%}" role="button">BACK</a>
        <input class="btn btn-success btn-sm"  type="submit" value="Submit">
        <a class="btn btn-danger btn-sm" href="{% url 'customer'%}" role="button">CANCEL</a>
        <br><br><br>
      </div>

</form>
{% endblock content%}

************my view.py is as under*********
def add_service_view(request):
    template_name = 'mis/Add-service.html'
    form = create_service_form()
    if request.method == 'POST':
        form = create_service_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('customer')
    return render(request, template_name, {'form':form})

***************my models.py is as under*********
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

cust_type = [('CF','Confidential'),('OMR', 'OMR based'),('OTH', 'Any other')]
class customer_model(models.Model):
    name                = models.CharField("Name",max_length = 100, null= True)
    address             = models.CharField("Address",max_length = 200, null = True)
    cust_type           = models.CharField("Customer Type",max_length= 100, null = True, choices = cust_type)
    start_date          = models.DateField("Date",auto_now= False, auto_now_add = False)
    cust_email          = models.EmailField("Email Address",max_length = 100, null = True)
    cust_phone          = models.IntegerField("Phone Number",null = True)
    cust_description    = models.TextField("Customer Description",blank = True)
    timestamp           = models.DateTimeField(auto_now_add =True, auto_now =False)
    Updated             = models.DateTimeField(auto_now=True, auto_now_add = False)

**Expected behavior**

**Console errors**
- No error on django console.
- No error on JavaScript console.

**Paste-bin**
The page is showing up but the date-picker calendar is not. The paste-bin link
of the HTML source of the page is http://...

**Setup Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser version [e.g. 22]
 - Python version [e.g. 3.7]
 - Django version [e.g. 2.1]
 - Bootstrap version [e.g. 3/4]
 - jQuery version [e.g. 1.7.1]

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

[configuration_page]: https://monim67.github.io/django-bootstrap-datepicker-plus/configure/
[troubleshooting_page]: https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html

**Comment by monim67** [comment]
Closing pre v5 issues as stale, starting from v5 the package presents informative error messages to address such issues.
