### ISSUE TITLE
end_of() field doesn't respect locale on first appearance

### ISSUE THREAD

**Issue by amethystdeceiver** [monim67/django-bootstrap-datepicker-plus#5]
I set up a pair of date range fields using `start_of()` and `end_of()`. The start field is OK, but the end field shows the picker in English the first time I click on the input. Only if I close and reopen it, it uses the specified locale.

Here's the code excerpt (w/ django-filters):
```
datepicker_args = {
    'format': '%d.%m.%Y',
    'options': { 'showClose': False, 'minDate': '2013-01-01', 'locale': 'ru' }
}
publishedFrom = django_filters.DateFilter(field_name='notification__published', lookup_expr='gte',
                                           widget=DatePickerInput(**datepicker_args).start_of('published'))
publishedTo = django_filters.DateFilter(field_name='notification__published', lookup_expr='lte',
                                           widget=DatePickerInput(**datepicker_args, attrs={'placeholder': 'по'}).end_of('published'))
```

**Comment by monim67** [comment]
Is this a model form? can you share paste-bin of the form class and view class you are using? I cannot reproduce the error so far.

**Comment by amethystdeceiver** [comment]
Sorry for the delay. Yes, it's a model form. Making an adequate paste-bin is a bit complicated, but basically I'm using standard functionality from `django_tables2` and `django_filter`. The view inherits from `FilterView` and `SingleTableMixin`, and the form is generated by `django_filter`. Here's a attempt for relevant bits of code: https://pastebin.com/chQbUcLa

Meanwhile, while trying to find a solution for another problem (which is the 'to' input widget allowing to select only today's date if 'from' input is empty), I was messing with the js code a bit. I have no idea what magic this is, but it seems like changing this bit in `datepicker-widget.js` somehow helps both problems:
```javascript
...
$.each(datepickerDict, function (id, to_picker) {
        if (to_picker.linked_to) {
            var from_picker = datepickerDict[to_picker.linked_to];
            var to_date = to_picker.datepickerdata.date();
            if (to_date) {
                from_picker.datepickerdata.maxDate(to_picker.datepickerdata.date());
            }
            var from_date = from_picker.datepickerdata.date();
            if (from_date) {
                to_picker.datepickerdata.minDate(from_picker.datepickerdata.date());
            }
...
```

Any thoughts?

**Comment by amethystdeceiver** [comment]
This would be more correct, perhaps:
```javascript
var to_date = to_picker.datepickerdata.date();
from_picker.datepickerdata.maxDate(to_date ? to_date : false);
var from_date = from_picker.datepickerdata.date();
to_picker.datepickerdata.minDate(from_date ? from_date : false);
```

I don't know if it's my particular case, but `from_picker.datepickerdata.date()` happens to be `null`, while `bootstrap-datetimepicker.js` specifies a condition for exactly boolean `false`, and this breaks everything:
```javascript
picker.minDate = function (minDate) {
    if (arguments.length === 0) {
        return options.minDate ? options.minDate.clone() : options.minDate;
    }

    if ((typeof minDate === 'boolean') && minDate === false) {
        options.minDate = false;
        update();
        return picker;
    }
...
```

**Comment by monim67** [comment]
You are absolutely right. Thanks for your time and patience to check it out. If the date is null, `minDate` should be unset i.e set to false. If you like to create a PR I would be very glad to merge it to the repository. The following seems nice to me.

            from_picker.datepickerdata.maxDate(to_picker.datepickerdata.date() || false);
            to_picker.datepickerdata.minDate(from_picker.datepickerdata.date() || false);
