### ISSUE TITLE
Changing width doesn't move calendar icon

### ISSUE THREAD

**Issue by kjthoward** [monim67/django-bootstrap-datepicker-plus#50]
I set the width of the datepicker using

`DatePickerInput(format='%m/%d/%Y',attrs={"style": "width:12.5em"})`

To match the size of other items in my form, however the calendar icon is still all the way over on the other side of the screen (I shrunk the screen to take the image otherwise it would be a tonne of white space):

![image](https://user-images.githubusercontent.com/40895027/88809840-7a05c500-d1ac-11ea-8d47-2a30cbaad50c.png)

If I don't use `attrs={"style": "width:12.5em"}` it takes up the entire width of the page, so what's the best way to set the width of the datepicker but one that also moves the calendar icon (or is there some way to hide that icon instead?)

**Comment by monim67** [comment]
I'd suggest the form width instead so that all inputs get same width without breaking bootstrap addons.
