### ISSUE TITLE
MEDIA is called twice

### ISSUE THREAD

**Issue by andytwoods** [monim67/django-bootstrap-datepicker-plus#51]
Hi,
I load manually load CSS and JS in my template for my ModelForm DateTime field. I dont load in {{ form.media.js }} as this is already loaded. 

The form works fine. But I get this error
`Uncaught TypeError: Cannot read property 'Constructor' of undefined`

Examination of html reveals that this JS and CSS is called, in MEDIA: https://github.com/monim67/django-bootstrap-datepicker-plus/blob/91400a3f80546eb046536e902f6825bdfd2f0836/bootstrap_datepicker_plus/_base.py#L50. Manually deleting that CSS and JS removes the console error. Note that the form _still works_ (as I manually add ncessary css and js).

Is there a setting for me to prevent MEDIA js and css being loaded? I've failed to google on this.

With many thanks,
Andy.

**Comment by monim67** [comment]
Closing pre v5 issues as stale. From v5 the error messages are more informative.
