### ISSUE TITLE
Format for Time is not working

### ISSUE THREAD

**Issue by RAVIKIRAN9912** [monim67/django-bootstrap-datepicker-plus#56]
**Describe the problem**
when i want to formate date with time i am format it like this date = forms.DateTimeField(widget=DateTimePickerInput(format='%Y-%m-%d %H:%i'))

that %i for minits is not working in widget it shows %i in widget

**Comment by monim67** [comment]
It should be `%I` instead.

Note: python formats are [no longer supported](https://github.com/monim67/django-bootstrap-datepicker-plus/issues/73#issuecomment-1312662806) from 5.0.0.
