### ISSUE TITLE
Unable to render/access media files when running on apache2 server

### ISSUE THREAD

**Issue by likhit-vivek** [monim67/django-bootstrap-datepicker-plus#59]
**Describe the bug**
The plugin worked fine when developing the django website locally, but after deploying it to aws and running it using apache2 server instead of the default django server, media files like `datepicker-widget.js` and `datepicker-widget.css` are all returning 404 (Not found) error.

**To Reproduce**
1. Deploy django project to AWS
2. Setup apache2 to run the django project in background
3. Access the website using public DNS of the instance

**Expected behavior**
All the necessary css and js should be accessible even when running on apache2

**Screenshots**

**Setup Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Browser version 
 - Python version 3.6.9
 - Django version 3.2
 - Bootstrap version 4
 - jQuery version

I tried giving full rwx access to apache2 for the folder `bootstrap_datepicker_plus` which is inside my virtual env and contains the css and js files but it didn't work

I don't know what else I need to change for this to work. Please help.

**Comment by monim67** [comment]
From version 5.0.0 the asset files are served from jsdelivr CDN by default. So no need to worry about serving static files on production servers.
