### ISSUE TITLE
How to use your datepicker

### ISSUE THREAD

**Issue by nelsonyan** [monim67/django-bootstrap-datepicker-plus#6]
Hi Munim: 
Thank you for the great work you have done for the community. I saw the demo for bootstrap 4 and that is exactly what I want to implement to my own site. First, I am just learning django with basic grasp of model, view, forms and template. I am able to input info (CharField) and display info on my site. I wanna add date and time input and that is when I came across your post on stackoverflow.
I was able to follow through most of your instruction. What I don't understand is that you have codes for forms.py, but not models.py. The 'custom form usage' section looks like models.py setup but can you import forms class and uses it in models.py? Can I create class with forms.Form and pass it as foreignkey into class IssueTracking? Please see my models.py and forms.pybelow. I greatly appreciate you expertise. Thank you.

models.py
`from django.db import models
from bootstrap_datepicker_plus import DatePickerInput

class IssueTracking(models.Model):
    po = models.CharField(max_length = 50, blank = False)
  
    def __str__(self):
        return self.po`

forms.py
`from bootstrap_datepicker_plus import DatePickerInput
from django import forms

class IssueInput(forms.ModelForm):
    class Meta:
        model = IssueTracking
        fields = '__all__'
        widgets = {
            'start_date': DatePickerInput(
            options={
                    "format": "MM/DD/YYYY", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                }
            ), # default date-format %m/%d/%Y will be used
        }`

**Comment by monim67** [comment]
The answer on stack-overflow and the README on this package assumes you have your models already setup and database migration done, which steps are nicely documented on [django docs site]. As you asked I am briefly explaining here.

Your `models.py` contains the models that holds the database fields of the entity as properties. You should have a `DateField` in your `IssueTracking` model. Then you need to migrate the model to create database table for that model. Then you can use the model to create Forms, then you can use the forms in your Views.

**models.py**

    class IssueTracking(models.Model):
        po = models.CharField(max_length = 50, blank = False)
        start_date = DateField()
        a_time_field = TimeField()
        a_datetime_field = DateTimeField()

        def __str__(self):
            return self.po

**Comment by monim67** [comment]
The error indicates `bootstrap4` is not present in your `INSTALLED_APPS` list, just install `django-bootstrap4` and add `bootstrap4` to the list. You don't need to add CDN bootstrap resources, the tags above will add the JavaScript and CSS resources for you including jQuery.

**Comment by nelsonyan** [comment]
ok, the web site is running now. but the entry field is missing the icon and there is no calendar poup. 
There is no error message. I did include BOOTSTRAP4 = {'include_jquery': True,} in settings.py file (at the very bottom of the file). I include my model and form.py. Do you see anything wrong here? Thank you

![capture](https://user-images.githubusercontent.com/42480417/44293461-4ea49c80-a259-11e8-8c8a-10365e504828.JPG)

models.py
`from django.db import models
class IssueTracking(models.Model):
    po = models.CharField(max_length = 50, blank = False)
    date_time = models.DateTimeField()
    def __str__(self):
        return self.po`

forms.py
`from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms
from amazon.models import IssueTracking
class IssueInput(forms.ModelForm):
    class Meta:
        model = IssueTracking
        fields = '__all__'
        widgets = {
            'date_time': DateTimePickerInput(
            options={
                    "format": "MM/DD/YYYY hh:mm A", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                }
            ), # default date-format %m/%d/%Y will be used
        }`

**Comment by monim67** [comment]
Please provide github link of your project

**Comment by nelsonyan** [comment]
ok, thanks. Let me get back to me soon

**Comment by nelsonyan** [comment]
Hi Munim. I added you as collaborator for django-datetime-picker. here is invite link 
https://github.com/nelsonyan/django-datetime-picker/invitations

a screen shot of app version in my conda virtual environment.
![capture](https://user-images.githubusercontent.com/42480417/44351124-0fe82f80-a46f-11e8-9e1f-26321f0dfd10.JPG)

What I notice is that after I pip install bootstrap4, the navbar dropdwon link on my base.html stops working. I have to comment out the 3rd script line at the bottom for bootstrap4.0.0 to make dropdown link work again. I comment out the 1st and 2nd one. the datatime picker is still not functioning properly
Thank you very much for all the help

**Comment by MSBPeace** [comment]
I had some similar issues getting this to work with django and bootstrap 4,
what ended up fixing stuff for me was:

Including the following (after reading the source of the example)
```
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" type="text/css"
        media="all" rel="stylesheet" />

# to get the icons to work right
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
```

and for JS

```
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="//cdn.rawgit.com/monim67/django-bootstrap-datepicker-plus/master/bootstrap_datepicker_plus/static/bootstrap_datepicker_plus/js/datepicker-widget.js"></script>
```

Hope this helps.

**Comment by monim67** [comment]
@MSBPeace, all these resources are added into the HTML by `{{ form.media }}` tag.

**Comment by nelsonyan** [comment]
@MSBPeace , holy molly it works now with the addition of the link and script! a couple feedback

1. I didn't include '<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" type="text/css"
        media="all" rel="stylesheet" />' It kinda distorted the format of the popup calendar. I also have to put the template tag in a table table-hover to make it look like what it is intended to be 

2. Is it possible to change the glyphicons? it seems to be using an I div but I cannot figure out how to change it with .css 
3. I commented out 'showclose, showclear, showtodaybutton' in the widget's options but they still shows up properly I don;t know why

Thank you for your help

**Comment by nelsonyan** [comment]
@monim67. Thank you for your help! I really appreciate your time and effort!

**Comment by monim67** [comment]
It is suggested to use django tags for the resources, check-out my commits on your repository.

**Comment by MSBPeace** [comment]
@nelsonyan I'm glad I managed to help

@monim67 I might have missed that indeed, thanks for pointing it out. Will refactor that when I have some time.
