### ISSUE TITLE
compatibility with Python 3.8 / Django 3.2?

### ISSUE THREAD

**Issue by GavinPen** [monim67/django-bootstrap-datepicker-plus#60]
Not strictly an issue - but are there any plans for a release which would be compatible with Python 3.8 / Django 3.2 / Bootstrap 5?
(or is release 3.0.5 already compatible with these?)

**Comment by monim67** [comment]
As far as I know it is compatible with Python 3.8 and Django 3.2, please let me know if I'm wrong. I do have plans for Bootstrap 5 down the road but I haven't quite figured out how to do that, any suggestions are welcome :+1:

**Comment by GavinPen** [comment]
Thanks for the quick reply!
I'll let you know if we discover if it's compatible with Python 3.8 and Django 3.2
