### ISSUE TITLE
How can I set tomorrow as default date for the control?

### ISSUE THREAD

**Issue by itonohito** [monim67/django-bootstrap-datepicker-plus#61]
I can not set default value of control to tomorrow (or any other date based on today()). I tried to create custom function, something like:
`
def rec_stopdate_default():
    return (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d %H:%M:%S")
` 
and later in ModelForm definition:
`
    time_stop = forms.DateTimeField(widget=DateTimePickerInput(
        options={
            'defaultDate': rec_stopdate_default(),
        },
    ).end_of("schedule"))

`
but looks like it's calculated just once on server restart, but not every time django form is opened.

Can you help my with that?

**Comment by monim67** [comment]
Starting from v5 this JavaScript options can be set in template files, see customization section in the docs.
