### ISSUE TITLE
Cannot import name 'DatePickerInput' from 'bootstrap_datepicker_plus'

### ISSUE THREAD

**Issue by sroywu** [monim67/django-bootstrap-datepicker-plus#66]
**Describe the bug**
getting error "cannot import name 'DatePickerInput' from 'bootstrap_datepicker_plus'" when using version 3.0.6

**To Reproduce**
1. From a working django web app, update with 3.0.6, deploy in debug mode
2. Reach a page using a DatePicker
3. See error
4. Repeat with version 3.0.5
5. No error

**Expected behavior**
Import should occur successfully

**Setup Information (please complete the following information):**
 - Python 3.8
 - Django version 3.2.9
 - python:3.8.3-slim-buster Docker base image
 - django boostrap 4.21 (bootstrap4)

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

[configuration_page]: https://monim67.github.io/django-bootstrap-datepicker-plus/configure/
[troubleshooting_page]: https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html

**Comment by monim67** [comment]
Please use the following
```py
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
```

**Comment by sroywu** [comment]
Is there any release notes I can look at to find any other interface breaking changes? Thanks!

**Comment by monim67** [comment]
Release notes are not maintained for this project. I have dropped the release, will create new release updating major version number. Sorry for the inconvenience.

**Comment by sroywu** [comment]
Ok no worries. I appreciate your contributions to the project! I will look at the changes in git README.
