### ISSUE TITLE
Django 4.0 release Dec 7th

### ISSUE THREAD

**Issue by sroywu** [monim67/django-bootstrap-datepicker-plus#68]
**Describe the problem**
Release notes for django 4.0:
https://docs.djangoproject.com/en/4.0/releases/4.0/

I am getting a template rendering error in datepicker:

    Exception Type: | TemplateSyntaxError
    Invalid block tag on line 1: 'ifnotequal', expected 'empty' or 'endfor'. Did you forget to register or load this tag?

With reference to:

    In template /usr/local/lib/python3.8/site-packages/bootstrap_datepicker_plus/templates/bootstrap_datepicker_plus/input.html, error at line 1
    <input type="{{ widget.type }}" name="{{ widget.name }}"{% if widget.value != None and widget.value != "" %} value="{{ widget.value }}"{% endif %}{% for name, value in widget.attrs.items %}{% ifnotequal value False %} {{ name }}(...)

The last `{% ifnotequal value False %}` is the underlined error. Now not sure if there is a problem with datepicker vs a bug in django v4.0 but there doesn't seem to be a change in the release notes of django 4 related to that so it looks like a django 4 bug, not a date picker one. Posting here in case I got it mixed up.

**To Reproduce**
Switch between django 3 and 4 with a known working page.

**Setup Information (please complete the following information):**
 - OS: docker python:3.8.3-slim-buster (debian based I think)
 - Python version 3.8.3
 - Django version 4.0 dec 7th release
 - Bootstrap version 4

If it turns out to be a django 4 bug, let me know how I can help report to the django project.

**Comment by monim67** [comment]
A new release (version 4.0.0) with the fix has been published.

**Comment by luigi370** [comment]
@sroywu you can try my fork for now.
django-bootstrap-datepicker-plus = {editable = true, ref = "master", git = "https://github.com/luigi370/django-bootstrap-datepicker-plus.git"}

**Comment by monim67** [comment]
@luigi370 I tested it before release and found it working, can you recheck and verify?
