### ISSUE TITLE
Cannot import DatePickerInput

### ISSUE THREAD

**Issue by MWH-Rookie** [monim67/django-bootstrap-datepicker-plus#71]
Hi

I  am using a chroot (Debian Buster on armel) and want to use the datepicker in a django app. I did this before in another chroot with django-bootstrap-datepicker-plus==3.0.5, but now I have django-bootstrap-datepicker-plus-4.0.0.

When I start my django app as usual with /bin/gunicorn3 -w 3 abrechnung.wsgi:application --bind 0.0.0.0:7777 I get a new error message, when I get to the app in the browser:

 File "/home/work/MyDjango/project/app_a/forms.py", line 7, in <module>
    from bootstrap_datepicker_plus import DatePickerInput
ImportError: cannot import name 'DatePickerInput' from 'bootstrap_datepicker_plus' (/usr/local/lib/python3.7/dist-packages/bootstrap_datepicker_plus/__init__.py)

I have no idea where this comes from? I already uninstalled and installed the datepicker again (wget from the current wheel (https://pypi.org/project/django-bootstrap-datepicker-plus/#files) and then python3 -m pip install that_wheel.

Do you have any advice for me?

Best regards

**Comment by MWH-Rookie** [comment]
Can it be that the _ _ init _ _ .py file has to be modified to import the widgets.py?

**Comment by monim67** [comment]
Duplicate to #66.
