### ISSUE TITLE
Formats "L" (Moment) and "%x" (python datetime)

### ISSUE THREAD

**Issue by ouhena** [monim67/django-bootstrap-datepicker-plus#73]
Maybe the map ("L", r"%x") could be added to format_map in the BasePickerInput class. It seems to be ok for 'en' and 'fr' locales, but I can't test for other locales.

**Setup Information (please complete the following information):**
 - OS: Linux
 - Browser Firefox 96.1.0esr
 - Python version 3.7
 - Django version 3.2
 - Bootstrap version 4
 - jQuery version 3.3.1
 - Moment version 2.9.0

**Comment by monim67** [comment]
From 5.0.0 python formats are no longer supported, only moment formats are accepted for simplicity. Hence format mapping is no longer required.
