### ISSUE TITLE
Replace CDN with Local Static Files

### ISSUE THREAD

**Issue by nschaeferComnet** [monim67/django-bootstrap-datepicker-plus#76]
**Is your feature request related to a problem? Please describe.**
form.media includes lib's from the CDN, so it wont work when the usage is local

**Describe the solution you'd like**
Can we have a way to overwrite the form.media to use local static paths instead of the usage of CDN?

**Additional context**
Local Files would prevent unwanted changes as happened before with for example NPM packages

**Comment by J-hanks** [comment]
Fixed this in my fork

**Comment by monim67** [comment]
From version 5.0.0 media urls can be overridden to use local static path. Details on [customization](https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/customization.html).
