### ISSUE TITLE
Bootstrap CDN or download?

### ISSUE THREAD

**Issue by ncottrill** [monim67/django-bootstrap-datepicker-plus#8]
I am attempting to use this in a Django 2.0+ project. I am new to web development in Django.

The demo for this project looks great! Thank you for posting this. 

I cannot get Django tags to resolve. I have only this Bootstrap link in a base.html template //maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css. Do I need to actually download Bootstrap 3? The instructions are clear except for this detail about Bootstrap files.

**Setup Information (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - Python version [3.6.4]
 - Django version [2.0.4]
 - Bootstrap version [3 via CDN]
 - jQuery version [?]

**Comment by monim67** [comment]
You need to install python package django-bootstrap3 or django-bootstrap4, then you need to follow the steps in the README file. If you get stuck about tags, you can check the demo_project included with the repository to see how to set base layout and include resources files to your template.

**Comment by ncottrill** [comment]
Thank you Monim. Below is the error I see, so it is a tags issue. I will install django-bootstrap3.

<img width="1023" alt="screen shot 2018-09-01 at 4 45 47 pm" src="https://user-images.githubusercontent.com/14022160/44950518-dddbb380-ae06-11e8-9d01-f8e0244ca126.png">

**Comment by ncottrill** [comment]
Fixed and working, Monim.

I had to install django-bootstrap3. Then, add it to the settings.py installed apps list. These were the missing steps for my setup. Thank you for your help! You can close this if you like 👍
