### ISSUE TITLE
The pickers do not open

### ISSUE THREAD

**Issue by ShlomoCode** [monim67/django-bootstrap-datepicker-plus#81]
**Describe the bug**

**To Reproduce**
very simple! Go to your demo page: https://monim67.github.io/django-bootstrap-datepicker-plus/Bootstrap4.html
And try opening a date picker/time picker.

**Expected behavior**
That the selector will open and let me choose a date... 😀 

**Screenshots**
![CleanShot 2022-09-07 at 23 12 05](https://user-images.githubusercontent.com/78599753/188968278-72a2cd1c-0686-4290-8e65-413133d660bf.gif)

**Setup Information (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Browser version 105.0.5195.102
 - Python version [e.g. 3.7]
 - Bootstrap version 4
I didn't bring the details of my project here, because even in the demo you created it doesn't work...

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

[configuration_page]: https://monim67.github.io/django-bootstrap-datepicker-plus/configure/
[troubleshooting_page]: https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html

@monim67

**Comment by WildHagai** [comment]
I've got the same bug on Windows 11, chrome 105.0.5195.53

**Comment by monim67** [comment]
If anyone still encounters it, you might just need to clear the browser cache.

**Comment by ShlomoCode** [comment]
How do you choose a time? All fields open date picker only.
