### ISSUE TITLE
Failing to validate DD/MM/YYYY format

### ISSUE THREAD

**Issue by jacopsd** [monim67/django-bootstrap-datepicker-plus#82]
When using the format DateTimePickerInput(options={"format": "DD/MM/YYYY HH:mm"})

The submitted form fails to validate when a date is entered  in this same format.
It seems it expects MM/DD/YYY HH:mm?

**Comment by monim67** [comment]
Duplicate #15

**Comment by jacopsd** [comment]
Thank you for the hint. Indeed, this solves the date format issue.

Now still the time shows UTC time instead of local time. How to solve this pls?

**Comment by monim67** [comment]
Sorry for the late response, you need to set time zone in Django settings.
