### ISSUE TITLE
fails to identify bootstrapVersion

### ISSUE THREAD

**Issue by WernerGo** [monim67/django-bootstrap-datepicker-plus#83]
**Describe the problem**
Using Boostrap5, Django 4.1.2, Python 3.10.2, macOS bigsur got an javascript error on console caused in the file "datepicker-widget.js". The variable boostrapVersion is not assigned with a proper value.
After manually setting the variables isBootstrap4 and isBootstrap5 with false / true everything works fine.

**Comment by monim67** [comment]
Resolved in 5.0.0.
