### ISSUE TITLE
Widget is initialised with wrong date string for European locals

### ISSUE THREAD

**Issue by christianwgd** [monim67/django-bootstrap-datepicker-plus#85]
**Describe the bug**
I'm trying to edit a date or datetime object. If this has a value of "23.11.2022 19:52" (db value "2022-11-23 19:52") it is displayed in the form as "20.11.0023 19:52". This is a problem for European locals ("de", "fr", "es", "it", ...), but not for "en-us". 

I've created a minimum example to investigate the problem in https://github.com/christianwgd/datepicker

**Expected behavior**
Show the date string in the form as "23.11.2022 19:52"

**Screenshots**
See example app.

**Setup Information (please complete the following information):**
 - OS: macOS 12.6
 - Browser Tested with recent Safari, Chrome, FireFox
 - Python version 3.10.4
 - Django version 4.1.3
 - Bootstrap version 5
 - jQuery version 3.6.0

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

**Comment by laurentiurosu-04** [comment]
Hi, I'm having the same issue with timezone 'Europe/Bucharest' on edit.
[https://i.ibb.co/hB3ZhNx/Screenshot-2022-11-23-141736.png](url)

**Comment by monim67** [comment]
Thanks for your reproducible example, it helped resolve it swiftly. The fix is released with version [5.0.1](https://github.com/monim67/django-bootstrap-datepicker-plus/releases/tag/5.0.1).

**Comment by user8-9w37** [comment]
Follow-up to this issue, after updating to `5.0.1`, the date formats are showing as `YYYY-MM-DD` instead of `DD/MM/YY` in eng-uk by default. I understand this is ISO, but will this remain in future updates or should I implement a local change to revert the default back to `DD/MM/YY`?

**Comment by christianwgd** [comment]
Thanks for the fast fix
