### ISSUE TITLE
ModuleNotFoundError: No module named 'django_bootstrap_datepicker_plus'

### ISSUE THREAD

**Issue by SKAv81** [monim67/django-bootstrap-datepicker-plus#89]
Hello, I need help here.. I have installed 'django_bootstrap_datepicker_plus' in my project virtual environment.. but i get this error - ModuleNotFoundError: No module named 'django_bootstrap_datepicker_plus'.. I have added it to installed_apps, tried upgrade etc and am sure it is installed.. still not sure why I am getting this message.. can anyone please help?

**Comment by smunoz-ml** [comment]
You have to add it to INSTALLED_APPS using `bootstrap_datepicker_plus`, not `django_bootstrap_datepicker_plus`
