### ISSUE TITLE
Lost Functionallity

### ISSUE THREAD

**Issue by jjulian91** [monim67/django-bootstrap-datepicker-plus#90]
After update from V3.X all functionality to modify the datepicker via JS/Jquery has been stripped 

**To Reproduce**
Install V5.X

**Expected behavior**
JQuery/Javascript to be able to update options of the datepicker.

**Comment by monim67** [comment]
From v4 customization has been greatly improved, details on [the doc](https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/customization.html).

**Comment by jjulian91** [comment]
The issue is that these seem to be immutable widgets.   JS/Jquery cannot touch the options after the form was rendered.
