### ISSUE TITLE
form.media was not loaded?

### ISSUE THREAD

**Issue by RichardWoj** [monim67/django-bootstrap-datepicker-plus#91]
**Describe the problem**
I followed the walkthrough tutorial to implement the pickerdate widget on a date field. Unfortunately when the page is rendered, I have a message displayed closed to the field saying "form.media was not loaded, did you forget to add it to template? This message is only visible when DEBUG=True"

**To Reproduce**

**Expected behavior**
Picking a date

**Console errors**
- No error on django console.
- No error on JavaScript console.

**Paste-bin**
The page is showing up but the date-picker calendar is not. The paste-bin link
of the HTML source of the page is http://...

**Setup Information (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 11
 - Browser [e.g. chrome, safari] Edge 
 - Browser version [e.g. 22] 110.0.1587.57
 - Python version [e.g. 3.7] 3.11.1
 - Django version [e.g. 2.1]: 4.1.5
 - Bootstrap version [e.g. 3/4]: 5
 - jQuery version [e.g. 1.7.1] 3.4.1

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

[configuration_page]: https://monim67.github.io/django-bootstrap-datepicker-plus/configure/
[troubleshooting_page]: https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html
<img width="368" alt="screenshot" src="https://user-images.githubusercontent.com/45973126/222509107-fc5c5ae9-5e44-48fc-abcb-ab694fe37996.png">

**Comment by monim67** [comment]
This is a validation message pointing out what you've missed while following the tutorial. Compare your template with with walkthrough template and add form media into your template, this message will go away.
